### ISSUE TITLE
Augeas lens should not fail on comments

### ISSUE THREAD

**Issue by jyaworski** [camptocamp/puppetfile-updater#13]
``` shell
joseph.yaworski@jyaworski-mbpr ~/puppet % awk 'NR >= 98 && NR <= 101' Puppetfile
mod 'mod', #This module is essentially dead upstream
#        :git    => 'https://github.com/somemod/puppet-somemod.git',
#        :commit => 'e4e9ab4348a72339b19e901dcb4658609295de1f'
         :local  => 'true'
```

The above causes the augeas lens to fail on all three lines containing comments. Can the augeas lens support comments?

**Comment by raphink** [comment]
The lens supports comments in general, but not comments inside entries.

**Comment by raphink** [comment]
I opened https://github.com/hercules-team/augeas/pull/620 to fix this. That had me sweat quite a bit :wink:
