### ISSUE TITLE
augeas lens don't support latest Puppetfile syntax

### ISSUE THREAD

**Issue by vchepkov** [camptocamp/puppetfile-updater#19]
augeas lens in updater fails to process latest syntax in Puppetfile, for example

```
mod 'classification',
  :git => 'ssh://git@stash/bp/puppet-classification.git',
  :branch => :control_branch
```

task fails:

```
Failed to parse Puppetfile at line 2, character 56: Iterated lens matched less than it should
```

There are several improvements have been added by r10k which make it easier to create dynamic environments, here is an example form a working puppetfile:

```
mod 'report_slack',
  :git    => 'ssh://git@stash/bp/report_slack.git',
  :branch => :control_branch,
  :default_branch => 'master'

mod 'site',
  :git    => 'ssh://git@stash/bp/puppet-site.git',
  :branch => 'production',
  :install_path => '.'

```

It would be nice to extend lens to support them.

Thanks
Vadym

**Comment by vchepkov** [comment]
lens was fixed in upstream, thank you https://github.com/hercules-team/augeas/pull/619

**Comment by raphink** [comment]
Yes, I guess I could copy the changes here, too.

**Comment by raphink** [comment]
Updated lens from upstream in d18bc00
