### ISSUE TITLE
gem install issue

### ISSUE THREAD

**Issue by brettswift** [camptocamp/puppetfile-updater#6]
I'm kind of at a loss with installing this gem on OSX.   Problems with native extensions.  I usually have problems installing nokogiri, but that one is installed.  Most of the internet seems to have this problem with RHEL or Ubuntu...  and installing a ruby-dev package helps. 

I did a `brew install augeus` first, no luck. 

This one seems to help most OSX guys, but not me: 
http://stackoverflow.com/questions/22352838/ruby-gem-install-json-fails-on-mavericks-and-xcode-5-1-unknown-argument-mul

I have rbenv configured by boxen, which I'm surprised doesn't figure this out..   however: 

```
/opt/rubies/2.1.2/bin/ruby extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/opt/rubies/2.1.2/bin/ruby
    --with-augeas-config
    --without-augeas-config
    --with-pkg-config
    --without-pkg-config
extconf.rb:27:in `<main>': augeas-devel not installed (RuntimeError)

extconf failed, exit code 1
```

Do you have this successfully installing on OSX ?

**Comment by jlambert121** [comment]
I gave up getting ruby-augeas to install in OSX and just built a VM.  The ruby-augeas gem hasn't been updated since 2013 so I'm thinking it's pretty much abandoned.
