### ISSUE TITLE
yet another not working issue

### ISSUE THREAD

**Issue by tampakrap** [camptocamp/puppetfile-updater#7]
Hello, I tried yesterday to use this gem without success. A few data first: [my current puppetfile](https://gist.github.com/tampakrap/84f234479c1ea0dd316a). I tried to simplify it as well, by removing all the content and leaving only one line like:

``` ruby
mod 'abrader/gms', '1.0.1'`
```

My Rakefile is copy-pasted from the example (using my real github credentials). I tried to debug it a bit and I noticed that it never enters the mpath loops (tried to print inside there the mpath value or a random debug message, none of which were ever printed). The config.debug is set to true, but I get no output (which is reasonable since I never enter the loops). aug.match('/augeas/files/Puppetfile/error').size is zero, so the Puppetfile seems properly parsed. I am stuck here as my augeas knowledge is non-existent, thus I would really appreciate any pointers on how to further debug

**Comment by tampakrap** [comment]
Forgot to mention that I touched the versions of a few modules to be into lower versions, thus I am definitely expecting updates. But I believe that is not really the point, since it never enters the aug.match loops

**Comment by tampakrap** [comment]
Feel free to also ping me on IRC, I'd be glad to provide any further info (tampakrap on freenode)

**Comment by bastelfreak** [comment]
I run into the same issue. The related code:

https://github.com/camptocamp/puppetfile-updater/blob/76675cba292f0b8a0f2031e330fd83ef739bff22/augeas/lenses/puppetfile.aug#L45

The regular expression looks a bit strange. I'm not sure for which format this was written, but it doesn't match the common format that @tampakrap and I use (and also forge.puppet.com suggests).

**Comment by lutter** [comment]
It looks like there's an extra backquote at the end of the line in the initial example. With that backquote, Augeas refuses to parse the file, with the backquote removed, it parses it successfully.

Is that the problem or am I looking at the wrong thing ?

@bastelfreak the regexp on line 45 is correct: it disallows ':' in the quoted string so that it can tell the version from options that might follow the version. There's probably other ways to achieve that, but they'd be more complicated.

**Comment by raphink** [comment]
Closing this as this is an old issue and there's no reason why this wouldn't parse (unless it was a problem with the extra backtick).
